server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: caracol-msvc-tienda
          uri: lb://caracol-msvc-tienda
          predicates:
            - Path=/api/v1/tienda/**