server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: caracol-msvc-tienda
          uri: lb://caracol-msvc-tienda
          predicates:
            - Path=/api/v1/tienda/**
        - id: caracol-msvc-mistral
          uri: lb://caracol-msvc-mistral
          predicates:
            - Path=/api/v1/mistral/**
        - id: caracol-msvc-zunpr
          uri: lb://caracol-msvc-zunpr
          predicates:
            - Path=/api/v1/zunpr/**