server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: pvc-caracol-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
