server:
  port: 9050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=API_VEDADO
    username: sa
    password: Destevezd.89
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
#    open-in-view: false
  liquibase:
    change-log: classpath:db.changelog.xml
#logging:
#  level:
#    org:
#      hibernate:
#        SQL=debug:
#      springframework: DEBUG