server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=MCSV_PARTES
    username: sa
    password: Destevezd.89
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2022Dialect
      ddl-auto: update
  liquibase:
    change-log: classpath:db.changelog.xml
springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
#  packagesToScan: pvc.caracol.empresarial.controller