server:
  port: 9012

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=MCSV_CINAD
    username: sa
    password: Destevezd.89
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2022Dialect
      ddl-auto: update
  liquibase:
    change-log: classpath:db.changelog.xml