server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
#logging:
#  level:
#    org:
#      hibernate:
#        SQL=debug:
#      springframework: DEBUG

springdoc:
  api-docs:
    enable: true
  swagger-ui:
    enable: true
    operations-sorter: method
    tags-sorter: alpha
##  packagesToScan: pvc.caracol.empresarial.controller