server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
#logging:
#  level:
#    org:
#      hibernate:
#        SQL=debug:
#      springframework: DEBUG